service: sherlock
runtime: nodejs10
env: standard
automatic_scaling:
  min_instances: 0
  max_instances: 1
network:
  forwarded_ports:
    - 8000

handlers:
  - url: /.*
    script: auto
    secure: always